website/log/urls.py
#!python
# log/urls.py
from django.conf.urls import url
from . import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

website/project/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/', views.new, name='new'),
    url(r'^(?P<perfil_id>\d+)', views.step, name='step'),
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^audit/', include('audit.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^documents/', include('documents.urls')),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'login/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
    url(r'^register/', include('register.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

website/project/models.py
# -*- coding: utf-8 -*- 
from __future__ import unicode_literals

from django.db import models
from audit.models import Type
from register.models import Client, Ey_employee, Client_employee
from status.models import List

# Tables related to Services
class Service_style(models.Model):
    service_name = models.CharField(max_length=100)
    service_description = models.CharField(max_length=250)

    def __str__(self):
        return self.service_name

class Activity(models.Model):
    project_name = models.CharField(max_length=250)
    start_date = models.DateField()
    end_date = models.DateField()
    audit = models.ForeignKey(Type, on_delete=models.PROTECT)
    client = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='clientes_projeto')
    status = models.ForeignKey(List, on_delete=models.PROTECT)
    ey_employee_master = models.ForeignKey(Ey_employee, on_delete=models.PROTECT)
    service_style = models.ForeignKey(Service_style, on_delete=models.PROTECT)
    activity_description = models.CharField(max_length=4000)
    activity_code = models.CharField(max_length=250, default="XXXXXXX")

    def __str__(self):
        return self.project_name
        
    def return_list(self):
        return [self.project_name,
                self.activity_description,
                self.client,
                self.ey_employee_master,
                self.start_date,
                self.end_date,
                self.audit,
                self.status]
    
    #def nome_cliente(self, cliente_projeto):
       # return Activity(project_name=self, client=cliente_projeto).get

class Activity_EY(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.PROTECT)
    ey_employee = models.ForeignKey(Ey_employee, on_delete=models.PROTECT)

class Activity_Client(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.PROTECT)
    client_employee = models.ForeignKey(Client_employee, on_delete=models.PROTECT)

website/project/forms.py
# -*- coding: utf-8 -*- 
from django.forms import ModelForm, Textarea
from django.contrib.auth.models import User
from project.models import Activity
from register.models import Ey_employee
from django import forms


class ActivityForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        initial = {
               'status': 1,
               'service_style': 1
              }
        if kwargs.has_key('initial'):
            kwargs['initial'].update(initial)
        else:
            kwargs['initial'] = initial
        # Initializing form only after you have set initial dict
        super(ActivityForm,self).__init__(*args, **kwargs)
        
        self.fields['status'].widget = forms.HiddenInput()
        self.fields['service_style'].widget = forms.HiddenInput()
        #self.fields['ey_employee_master'] = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=1))

    #def return_full_name(queryset):
    #    full_name_list = []
    #    for query in queryset:
    #        full_name_list.append(query.first_name + " " + query.last_name)
    #    return full_name_list


    class Meta:
        model = Activity
        fields = (
        'project_name', 'activity_description', 'start_date', 'end_date', 'client', 'audit', 'ey_employee_master',
        'status', 'service_style')
        widgets = {
            'activity_description': Textarea(attrs={'cols': 80, 'rows': 20}),
            'start_date': forms.DateInput(attrs={'class': 'datepicker'}),
        }

class Template_Upload(forms.Form):
    upload = forms.FileField(label='', required=False)


class Validation_Form(forms.Form):
    validate = forms.BooleanField(initial=True, widget=forms.HiddenInput())
    
    def __init__(self, *args, **kwargs):
        super(Validation_Form,self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'id': 'validate_id'}) 

website/project/views.py
# -*- coding: utf-8 -*-
# Libs de Django
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.template import Context
from django.utils.safestring import mark_safe
from django.core.files.storage import FileSystemStorage 
# Libs de Settings
from website.settings import BASE_DIR
# Libs de forms
from .forms import ActivityForm, Validation_Form
from documents.forms import NewDocumentForm
# Libs de models
from documents.models import Request, Received, Template
from project.models import Activity, Activity_Client
from status.models import Workflow
from register.models import Client_employee, Ey_employee
from status.models import List
from django.contrib.auth.models import User
from pandas import DataFrame
import shutil

import os
import datetime

# Create your views here.
def index(request):
    if request.method == 'POST':
        return HttpResponseRedirect("new")
    else:
        if request.user.is_superuser:
            print Activity.objects.all()
            return render(request, 'project/Activities_Dashboard.html', {'activity': Activity.objects.all()})
        elif not request.user.is_staff:
            client_employee_id = Client_employee.objects.get(client_user=request.user.id)
            activity_client_list = list(Activity_Client.objects.filter(client_employee=client_employee_id))
            project_client_list = []

            for act in activity_client_list:
                project_client_list.append(Activity.objects.get(id=act.activity_id))
            return render(request, 'project/Activities_Dashboard.html', {'activity': project_client_list})
        else:
            return render(request, 'project/Activities_Dashboard.html', {'activity': Activity.objects.filter(
            ey_employee_master=Ey_employee.objects.get(ey_employee_user_id=request.user.id))})


def new(request):
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect("index")
    else:
        form = ActivityForm()
    return render(request, 'project/new.html', {'form': form})


def check_if_path_exists(path):
    if os.path.exists(path) == False:
        os.makedirs(path)

def sending_email(email, template_list, email_page):
    subject = "Email de teste django"
    from_email = "ia.automation.tool@gmail.com"
    to = email
    message = get_template(email_page).render(Context({'template_list': template_list, 'BASE_DIR' : BASE_DIR}))
    msg = EmailMessage(subject, mark_safe(message), to=[to], from_email=from_email)
    msg.content_subtype = 'html'
    msg.send()

def update_status(project_id, choice):
    current_project = Activity.objects.get(id=project_id) 
    current_status = current_project.status_id
    current_workflow = Workflow.objects.get(workflow_current_status=current_status)
    
    if choice == 'success':        
        next_status = current_workflow.workflow_success_next_status
        print str(current_status) + " --> " + str(next_status)
    elif choice == 'fail':        
        next_status = current_workflow.workflow_fail_next_status
        print str(current_status) + " --> " + str(next_status)
    else:
        print "deu ruim..."
    
    current_project.status_id = next_status
    current_project.save()
    return "Status alterado de: " + str(current_status) + " para: " + str(next_status)
            
def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'project/upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'project/upload.html')

def file_received_verifier(request, options, not_received_control, doc_request):
    for item in doc_request:
        if Received.objects.filter(activity=item.activity,template=item.template):
            options[item.id] = 'Received'
        else:
            options[item.id] = 'Not Received'
            not_received_control = 1

def handle_uploaded_file(f,dyn_path,req):
    base_dir = BASE_DIR.replace("\\""", "/")
    defined_path = str(dyn_path) + str(req.send_counter) + "." + str(f.name)
    real_path = str(base_dir)+str(defined_path)
    with open(real_path, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
       
def compact_file_generator(request, folder_to_compact, file_format, path_of_folder):
    shutil.make_archive(folder_to_compact, file_format, path_of_folder)
            

def step(request, perfil_id):
    #Método destinado ao controle de passos do workflow
    act = Activity.objects.get(id=perfil_id)
    status_check = act.status
    options = {1: step_one,
               2: step_two,
               3: step_three,}

    return HttpResponse(options[status_check.id](request, perfil_id));

def step_one(request, perfil_id):
    print "STEP 1"
    activity = Activity.objects.get(id=perfil_id)
    templates = Template.objects.all()
    email_list = Activity_Client.objects.filter(activity_id=perfil_id)

    if request.method == 'POST':
        dropdown_list = request.POST.getlist("dropdown")
        df = DataFrame(zip(dropdown_list, templates))
        print df
        for email in set(dropdown_list):
            if "@" in email:
                filtered_templates =  list(df[df[0] == email][1])
                sending_email(email, filtered_templates, 'project/email.html')
                user_client_id = User.objects.get(email=email).id
                for template in filtered_templates:
                    client_emp_obj = Client_employee.objects.get(client_user_id=user_client_id)
                    try:
                        Request.objects.get(activity_id=perfil_id,
                            client_employee_id=Client_employee.objects.get(client_user_id=user_client_id).id,
                            ey_employee_id=Ey_employee.objects.get(ey_employee_user_id=request.user.id).id,
                            template_id=template.id,
                            send_counter=0)
                    except:
                        path_string = "/media/" + \
                                      str(activity.audit.id) + "." + str(activity.audit) + "/" + \
                                      str(activity.id) + "." + str(activity.project_name) + "/" + \
                                      "1.Documentos Recebidos" + "/" + \
                                      str(request.user.id) + "." + request.user.first_name + request.user.last_name + "/" + \
                                      str(client_emp_obj.id) + "." + User.objects.get(email=email).first_name + \
                                      User.objects.get(email=email).last_name + "/" + \
                                      str(template.id) + "." + template.template_name + "/"

                        Request(activity_id=perfil_id,
                            client_employee_id=Client_employee.objects.get(client_user_id=user_client_id).id,
                            ey_employee_id=Ey_employee.objects.get(ey_employee_user_id=request.user.id).id,
                            template_id=template.id,
                            send_counter=0,
                            request_path=path_string).save()

                        check_if_path_exists(BASE_DIR.replace("\\""", "/") + path_string)
        update_status(perfil_id, "success")
        return render(request, 'project/email_sender.html', {'activity':activity,'templates': templates, 'email_list': email_list})
    else:
        print "(ELSE)"
        return render(request, 'project/email_sender.html', {'activity':activity,'templates': templates, 'email_list': email_list})
        #return "blabla"

def step_two(request, perfil_id):
    print "STEP 2"
    actv = Activity.objects.get(id=perfil_id)
    doc_request = Request.objects.filter(activity__id=perfil_id)
    doc_request = list(doc_request)
    options = {}
    not_received_control = 0
    #Verificação antes do POST de quais documentos já foram enviados pelo cliente
    file_received_verifier(request, options, not_received_control, doc_request)
    #try:
    if request.method == 'POST':
        #request.session['_old_post'] = request.POST
        #Para cada item dentro de request, é montado o ID do botão (upload) pressionado.
        for req in doc_request:
            aux_myfile = req.id
            aux_mybutton = "mybutton_" + str(aux_myfile)
            req_object = req
            #Caso o botão (upload) pressionado seja correspondente com o POST, o upload do arquivo é realizado.
            if aux_mybutton in request.POST:
                
                if options[aux_myfile] != 'Received':
                    #Atribuição do documento selecionado para realizar Upload
                    myfile = request.FILES['myfile_'+str(aux_myfile)]
                    myfile_list = []
                    myfile_list.append(myfile)
                    if not (str(myfile.name).endswith('.zip') or str(myfile.name).endswith('.rar') or str(myfile.name).endswith('.7z')):
                        #Variável temporária para definição de path dinâmico para armazenamento de arquivos (esta variável deverá recever o valor referente à lógica de criação de pastas no MYSQL)

                        dyn_path = req.request_path
                        
                        #Novo método de upload de arquivos
                        handle_uploaded_file(myfile,dyn_path,req_object)

                        #Inclusão de linha contendo o arquivo recebido na tabela Received do MySQL
                        Received(received_name = req_object.template.template_name, 

website/project/templates/project/Activities_Dashboard.html
{% extends 'project/Template EY.html' %}

{% block content %}
{% load app_filters %}

    <h2 class="ey-h2-style"><a>Projetos</a></h2>
    <table>
            <th>Project Name</th>
            <th>Description</th>
            <th>Client</th>
            <th>Leader</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Audit Type</th>
            <th>Status</th>
            {% for act in activity %}
                <tr>
                    {% if act.status_id != 2 and request.user.is_staff != 1 %}
                        <td>{{act.project_name}}</td>
                    {% else %}
                        <td><a href="{{act.id}}">{{act.project_name}}</a></td>
                    {% endif %}
                    <td>{{act.activity_description}}</td>
                    <td>{{act.client}}</td>
                    <td>{{act.ey_employee_master.ey_employee_user.first_name}} {{act.ey_employee_master.ey_employee_user.last_name}}</td>
                    <td>{{act.start_date}}</td>
                    <td>{{act.end_date}}</td>
                    <td>{{act.audit}}</td>
                    <td>{{act.status}}</td>
                    <!--<td onclick="run(this)" id="status_{{forloop.counter}}" value="{{act.status_id}}">{{act.status}}</td>-->
                </tr>
            {% endfor %}
    </table>
    
    <form method="post">{% csrf_token %}
        <button class="button" action=""><span>New Project </span></button>
    </form>

    <a href="/documents/">
        <button class="button button2" type="submit2"><span>New Document</span></button>
    </a>

<script>
    function run(object) {
            if(document.getElementById(object.id).innerText == "Aguardando Documentos") {
            alert("Não Pode!");
            }
        }
</script>

{% endblock %}

website/project/templates/project/New.html
{% extends 'project/Template EY.html' %}

{% load static %}

{% block content %}
    <!-- <link rel="stylesheet" href="{% static "/project/style_new.css" %}"> -->
        
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

<div class="content-table" style="padding:0px">
<h2 class="ey-h2-style"><a class="ey_anchor_style" href="/project">Projetos</a> > Novo Projeto</h2>

    <div align="center">
            <form method="POST" class="basic-grey"> 
                <h1>Create Project</h1>
                {% csrf_token %}       
                    {{ form.as_p }} 
                <button class="button" type="submit"><span>Send </span></button>
            </form>
    </div>
</div>

{% endblock %}

website/project/templates/project/Project_Details_Step2.html
{% extends 'project/Template EY.html' %}

{% block content %}
{% load app_filters %}


        <h2 class="ey-h2-style"><a class="ey_anchor_style" href="/project">Projetos</a> > Detalhes do Projeto: {{activity.project_name}}</h2>
        <h3 class="ey-h3-style">Status: {{activity.status}}</i></h3>

        <table>
            <th>Project Name</th>
            <th>Document Name</th>
            <th>Description</th>
            <th>EY Requester</th>
            <th>File Selection</th>
            <th></th>
            <th>Status</th>
            {% for doc in documents %}
                <tr>
                    <td>{{doc.activity}}</td>
                    <td>{{doc.template}}</td>
                    <td>{{doc.template.template_description}}</td>
                    <td>{{doc.ey_employee.ey_employee_user.first_name}} {{doc.ey_employee.ey_employee_user.last_name}}</td>
                   
                        {% if options|get_dict_value:doc.id == "Not Received" %}
                        <form method="post" enctype="multipart/form-data">
                            <td>
                                {% csrf_token %}
                                <input type="file" id="myfile_{{doc.id}}" name="myfile_{{doc.id}}">
                            </td>
                            <td>
                                <button type=submit id="mybutton_{{doc.id}}" name="mybutton_{{doc.id}}">Upload</button>
                            </td>
                        </form>
                        {% else %}
                            <td>
                                {% csrf_token %}
                                <input type="file" id="myfile_{{doc.id}}" name="myfile_{{doc.id}}" disabled>
                            </td>
                            <td>
                                <button type=submit id="mybutton_{{doc.id}}" name="mybutton_{{doc.id}}" disabled>Upload</button>
                            </td>
                        {% endif %}
                  
                    <td>
                        <p id="options_{{doc.id}}">{{options|get_dict_value:doc.id}}</p>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <button class="button" type="submit"><span>Send </span></button>
        
{% endblock %}

website/project/templates/project/Project_Details_Step2_N.html
{% extends 'project/Template EY.html' %}

{% block content %}
{% load app_filters %}


    <div  class="content-table">
        <h2 class="ey-h2-style"><a class="ey_anchor_style" href="/project">Projetos</a> > Detalhes do Projeto: {{activity.project_name}}</h2>
        <h3 class="ey-h3-style">Status: {{activity.status}}</i></h3>


        <h1>Não existem registros</h1>
        
    </div>

{% endblock %}

website/project/templates/project/Project_Details_Step2_Success.html
{% extends 'project/Template EY.html' %}

{% block content %}
{% load app_filters %}


    <div  class="content-table">
        <h2 class="ey-h2-style"><a class="ey_anchor_style" href="/project">Projetos</a> > Detalhes do Projeto: {{activity.project_name}}</h2>
        <h3 class="ey-h3-style">Status: {{activity.status}}</i></h3>


        <h1>Success</h1>
        
    </div>

{% endblock %}

website/project/templates/project/Project_Details_Step3.html
{% extends 'project/Template EY.html' %}

{% block content %}
{% load app_filters %}
{% load static %}

        <h2 class="ey-h2-style"><a class="ey_anchor_style" href="/project">Projetos</a> > Status de recebimento de documentação: {{activity.project_name}}</h2>
        <h3 class="ey-h3-style">Status: {{activity.status}}</i></h3>

        
            
            {{validation}}
                <table>
                    <th>Project Name</th>
                    <th>Document Name</th>
                    <th>Description</th>
                    <th>EY Requester</th>
                    <th>Requested To</th>
                    <th>Upload Status</th>
                    <th>Resend Counter</th>
                    <th>Resend Request</th>
                    {% for doc in documents %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}    
                        <tr>
                            <td id="myactivity_{{doc.id}}" name="myactivity_{{doc.id}}">{{doc.activity}}</td>
                            <td id="mytemplate_{{doc.id}}" name="mytemplate_{{doc.id}}">{{doc.template}}</td>
                            <td id="mytemplate_description_{{doc.id}}" name="mytemplate_description_{{doc.id}}">{{doc.template.template_description}}</td>
                            <td id="myname_{{doc.id}}" name="myname_{{doc.id}}">{{doc.ey_employee.ey_employee_user.first_name}} {{doc.ey_employee.ey_employee_user.last_name}}</td>
                            <td id="mycliname_{{doc.id}}" name="mycliname_{{doc.id}}">{{doc.client_employee.client_user.first_name}} {{doc.client_employee.client_user.last_name}}</td>
                            <td>
                                {{options|get_dict_value:doc.id}}
                            </td>
                            <td id="mycounter_{{doc.id}}" name="mycounter_{{doc.id}}">{{doc.send_counter}}</td>
                            <td>
                                <button type=submit id="mybutton_{{doc.id}}" name="mybutton_{{doc.id}}">Resend</button>
                            </td>
                        </tr>
                    </form>
                    {% endfor %}
                </table>
                
                
                    <button class="button" onclick="myFunction()" type="submit"><span>Next </span></button>

                    <!--<a name="mydownload" id="mydownload" href="http://localhost:8000/media/downloads/media.zip" download>
                        <button class="button button2" name="mydownload" id="mydownload"><span>Download files </span></button>
                    </a>-->
                    
                <!--<form method="post" enctype="multipart/form-data" action="http://localhost:8000/media/downloads/{{file_name}}">
                    {% csrf_token %}       
                    <button class="button button2" name="mydownload" id="mydownload" value="Download">
                        <span>Download files </span>
                    </button>
                    
                </form>-->


                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}       
                    <button class="button button2" name="mydownload" id="mydownload" value="Download">
                        <span>Download files </span>
                    </button>
                    
                </form>

                <p id="demo"></p>
                <script>
                    function myFunction() {
                        if ({{not_received_control}} != 0){
                            if (confirm("There are not received files. Do you wish to continue?") == true) {
                                x = "You pressed OK!";
                                toggle()
                            } else {
                                x = "You pressed Cancel!";
                                set_to_false();
                            }
                            document.getElementById("demo").innerHTML = x;
                        }
                    }
                    
                    function set_to_false() {
                        document.getElementById('validate_id').value="False";
                    }
                    
                    function downloadFile(file)
                    {
                        window.location=file;
                    }
                    
                    function setFormAction() {
                        document.getElementById("mydownload").action = //some code to get the filename;
                    }
                    
                </script>
        

    


{% endblock %}

website/project/templates/project/Project_Details_Step3_Resend.html
{% extends 'project/Template EY.html' %}

{% block content %}
{% load app_filters %}


        <h2 class="ey-h2-style"><a class="ey_anchor_style" href="/project">Projetos</a> > Status de recebimento de documentação: {{activity.project_name}}</h2>
        <h3 class="ey-h3-style">Status: {{activity.status}}</i></h3>

                    <div align="center">
                        <form method="POST" class="basic-grey"> 
                            <h1>Resend Project Request</h1>
                            {% csrf_token %}       
                            <p id="myactivity_{{doc.id}}" name="myactivity_{{doc.id}}">
                                <label>Project Name</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{doc.activity}}" disabled>
                            </p>
                            <p id="mytemplate_{{doc.id}}" name="mytemplate_{{doc.id}}">
                                <label>Document Name</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{doc.template}}" disabled>
                            </p>
                            <p id="mytemplate_description_{{doc.id}}" name="mytemplate_description_{{doc.id}}">
                                <label>Description</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{doc.template.template_description}}" disabled>
                            </p>
                            <p id="myname_{{doc.id}}" name="myname_{{doc.id}}">
                                <label>EY Requester</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{doc.ey_employee.ey_employee_user.first_name}} {{doc.ey_employee.ey_employee_user.last_name}}" disabled>
                            </p>
                            <p id="mycliname_{{doc.id}}" name="mycliname_{{doc.id}}">
                                <label>Requested To</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{doc.client_employee.client_user.first_name}} {{doc.client_employee.client_user.last_name}}" disabled>
                            </p>
                            <p>
                                <label>Upload Status</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{options|get_dict_value:doc.id}}" disabled>
                            </p>
                            <p id="mycounter_{{doc.id}}" name="mycounter_{{doc.id}}">
                                <label>Resend Counter</label>
                                <input id="id_project_name" maxlength="250" name="project_name" type="text" value="{{doc.send_counter}}" disabled>
                            </p>
                            <p id="myreason_{{doc.id}}" name="myreason_{{doc.id}}">
                                <label>Resend Reason</label>
                                <textarea cols="80" id="activity_description" maxlength="4000" name="activity_description" rows="20" required=""></textarea>
                            </p>
                                
                            <button id="mybutton_resend_{{doc.id}}" name="mybutton_resend_{{doc.id}}" class="button" type="submit">
                                <span>Send </span>
                            </button>
                        </form>
                    </div>
  


{% endblock %}

website/project/templates/project/Template EY.html
<!DOCUMENT html>

{% load static %}
<html>
                {% if user.is_authenticated  %}
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="{% static "/project/reset.css" %}">
		<link rel="stylesheet" href="{% static "/project/style.css" %}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto" >
           <!--<link rel="stylesheet" href="{% static "/project/bootstrap.min.css" %}" >-->
            <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
	</head>
	

	<body>
		<main>

			<div class="ey-header-style"></div>
                 <div class="ey-subheader-style"></div>
			<h1 class="ey-h1-style">IA - Automation Tool</h1>
			<img class="ey-logo" src="{% static "/project/EYNewLogo.png" %}"/>

            {% if user.is_superuser  %}
                <a href="/register" class="create-group-button">Create User</a>
            {% endif %}
                 <a href="/logout" class="logout">Login teste</a>
                 <p class="welcome">Welcome, {{ user.first_name }} {{ user.last_name }}</p>

			<div class="content">
                 <div class="content-table">


                    {% block content %}
                    {% endblock %}


                </div>
			</div>



		</main>

	</body>
	
	    
	<footer class="ey-footer-style">
		<p class="p-footer-style">&copy EY</p>
		<p class="p-footer-style version-style">Version 0.0.1</p>	
	</footer>

{% else %}
    <p> Não esta autenticado</p>
{% endif %}
    
</html>

website/project/templates/project/email.html
<!DOCUMENT html> 

<p>
    Olá!
</p>
<p>
    Você esta recebendo os seguintes links para <strong>download</strong>:
</p>
<ul>
{% for template in template_list %}
<li>
    <a href="{{ BASE_DIR }}/{{ template.template_path }}">{{ template.template_name }}</a>
</li>
{% endfor %}
</ul>    
<p>
Att,
</p>
<p>
IA Automation Tool
</p>

website/project/templates/project/email_step2.html
<!DOCUMENT html> 

<p>
    Olá!
</p>
<p>
    Você esta recebendo os seguintes links para <strong>download</strong>:
</p>
<ul>
{% for template in template_list %}
<li>
    <a href="{{ BASE_DIR }}/{{ template.template_path }}">{{ template.template_name }}</a>
</li>
{% endfor %}
</ul>    
<p>
Att,
</p>
<p>
IA Automation Tool
</p>